services:
  dev:
    build: 
      context: .
      dockerfile: ./.build/Dockerfile
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
        - PY_VER=${PY_VER:-3}
        - R_VER=${R_VER:-4.3.2}
    tty: true
    stdin_open: true
    volumes:
      - .:/home/docker/workspace
      - renv:/home/docker/.cache/R/renv
volumes:
  renv:
    external: true
    
